kumuluzee:
  name: image-service-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  cors-filter:
    annotations:
      images-resource:
        allow-origin: "*"
        allow-subdomains: true
        supported-methods: "GET, POST, DELETE, HEAD, OPTIONS, PUT"

  logs:
    # Change host and port to working current logit.io account.
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                   <Configuration name="comments">
                       <Appenders>
                           <Console name="console" target="SYSTEM_OUT">
                               <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                           </Console>
                           <Socket name="logstash" host="b35aba1f-8a64-4f9b-8e1d-a399a1b56496-ls.logit.io"
                           port="18569" protocol="udp">
                               <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                           </Socket>
                       </Appenders>
                       <Loggers>
                           <!-- Default logger -->
                           <Root level="all">
                               <AppenderRef ref="console" level="info" />
                               <AppenderRef ref="logstash" level="trace" />
                           </Root>
                       </Loggers>
                   </Configuration>'

rest-config:
  maintenance-mode: true

